Repository ros2/geometry2, pull requests merged in 2019-06, with the labels that each got.

#120 Fix the MessageFilter init order.
  tf2_ros/include/tf2_ros/message_filter.h
Labels: in review

#123 Drop misleading ROS_* logging macros from tf2_monitor
  tf2_ros/src/tf2_monitor.cpp
Labels: bug, in review

#122 Allow tf2_monitor to be run with ROS command line args
  tf2_ros/src/tf2_monitor.cpp
Labels: enhancement, in review
