Repository ros2/geometry2, pull requests merged in 2019-05, with the labels that each got.

#105 Fix call to create_publisher after API changed
  tf2_ros/include/tf2_ros/static_transform_broadcaster.h
Labels: in review

#106 add LICENSE file
  LICENSE
Labels: in progress

#107 changes to avoid deprecated API's
  tf2_ros/include/tf2_ros/static_transform_broadcaster.h
  tf2_ros/src/tf2_monitor.cpp
  tf2_ros/src/transform_broadcaster.cpp
  tf2_ros/src/transform_listener.cpp
  tf2_ros/test/message_filter_test.cpp
Labels: in progress

#109 Tf2_msgs including actions
  tf2_msgs/CMakeLists.txt
  tf2_msgs/action/LookupTransform.action
  tf2_msgs/package.xml
Labels: in review

#90 Port tf2_kdl
  tf2_eigen/include/tf2_eigen/tf2_eigen.h
  tf2_eigen/test/tf2_eigen-test.cpp
  tf2_kdl/AMENT_IGNORE
  tf2_kdl/CMakeLists.txt
  tf2_kdl/include/tf2_kdl/tf2_kdl.h
  tf2_kdl/include/tf2_kdl/tf2_kdl/tf2_kdl.h
  tf2_kdl/package.xml
  tf2_kdl/scripts/test.py
  tf2_kdl/src/tf2_kdl/__init__.py
  tf2_kdl/src/tf2_kdl/tf2_kdl.py
  tf2_kdl/test/test_tf2_kdl.cpp
Labels: in review

#112 Remove stray semicolon causing compiler error when using -Werror=pedantic
  tf2_ros/include/tf2_ros/transform_broadcaster.h
Labels: in review

#115 enable pedantic for tf2_ros
  tf2_ros/CMakeLists.txt
  tf2_ros/include/tf2_ros/buffer.h
  tf2_ros/include/tf2_ros/message_filter.h
  tf2_ros/include/tf2_ros/static_transform_broadcaster.h
  tf2_ros/src/buffer.cpp
  tf2_ros/src/static_transform_broadcaster_program.cpp
  tf2_ros/src/tf2_echo.cpp
  tf2_ros/src/tf2_monitor.cpp
  tf2_ros/src/transform_listener.cpp
  tf2_ros/test/message_filter_test.cpp
Labels: in review

#111 Store dedicated transform listener thread as a std::unique_ptr
  tf2_ros/include/tf2_ros/transform_listener.h
  tf2_ros/src/transform_listener.cpp
Labels: enhancement, in review
