Repository ros2/geometry2, pull requests merged in 2019-10, with the labels that each got.

#173 Quiet the cast-function-type warning on GCC 8.
  tf2_py/CMakeLists.txt
Labels: enhancement

#178 [tf2] Use ament_target_dependencies where possible
  tf2/CMakeLists.txt
Labels: enhancement, in review

#151 Overwrite TimeCacheInterface type with a current input
  tf2/src/buffer_core.cpp
  tf2/test/simple_tf2_core.cpp
Labels: enhancement

#180 Rclcpp time convenience methods
  tf2_ros/include/tf2_ros/buffer.h
  tf2_ros/include/tf2_ros/buffer_interface.h
  tf2_ros/test/test_buffer.cpp
Labels: enhancement

#179 Remove template specialization for toMsg functions
  tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h
  tf2_geometry_msgs/test/test_tf2_geometry_msgs.cpp
Labels: in review
