Repository ros2/geometry2, pull requests merged in 2020-01, with the labels that each got.

#202 Porting more tests to tf2_ros
  tf2_ros/CMakeLists.txt
  tf2_ros/test/listener_unittest.cpp
  tf2_ros/test/py_test/test_buffer_client.py
  tf2_ros/test/test_buffer_client.cpp
  tf2_ros/test/time_reset_test.cpp
  tf2_ros/test/transform_listener_time_reset_test.launch
  tf2_ros/test/transform_listener_unittest.launch
Labels: enhancement

#203 Porting test_tf2
  test_tf2/AMENT_IGNORE
  test_tf2/CMakeLists.txt
  test_tf2/package.xml
  test_tf2/test/buffer_client_tester.launch
  test_tf2/test/buffer_client_tester.launch.py
  test_tf2/test/buffer_core_test.cpp
  test_tf2/test/permuter.hpp
  test_tf2/test/static_publisher.launch
  test_tf2/test/static_publisher.launch.py
  test_tf2/test/test_buffer_client.cpp
  test_tf2/test/test_buffer_client.launch.py
  test_tf2/test/test_buffer_client.py
  test_tf2/test/test_buffer_server.cpp
  test_tf2/test/test_convert.cpp
  test_tf2/test/test_convert.py
  test_tf2/test/test_message_filter.cpp
  test_tf2/test/test_static_publisher.cpp
  test_tf2/test/test_static_publisher.py
  test_tf2/test/test_tf2_bullet.cpp
  test_tf2/test/test_utils.cpp
Labels: enhancement, in progress

#214 Remove virtual keyword from overridden functions
  tf2_ros/include/tf2_ros/buffer.h
Labels: enhancement, in review

#226 tf2_tools update the shebang line
  tf2_tools/scripts/view_frames.py
Labels: enhancement

#227 [Eloquent backport] tf2_tools update the shebang line
  tf2_tools/scripts/view_frames.py
Labels: enhancement
