Repository ros2/geometry2, pull requests merged in 2020-02, with the labels that each got.

#201 Fix deprecated copy in tf2::Stamped<T>
  tf2/include/tf2/transform_datatypes.h
Labels: bug, enhancement, in review

#231 use target_include_directories
  tf2_geometry_msgs/CMakeLists.txt
  tf2_sensor_msgs/CMakeLists.txt
Labels: in review

#222 Style cleanup on tf2_py.cpp
  tf2_py/CMakeLists.txt
  tf2_py/include/python_compat.h
  tf2_py/package.xml
  tf2_py/src/tf2_py.cpp
  tf2_py/test/test_buffer_core.py
  tf2_py/tf2_py/__init__.py
Labels: enhancement

#241 Fix build error in Focal
  tf2_py/src/tf2_py.cpp
Labels: in review
